"""Progress tracking utility functions package.

This package contains utility functions for data serialization,
validation, and formatting in the progress tracking system.
"""

from .serializers import (
    serialize_task_progress,
    deserialize_task_progress,
    serialize_log_entry,
    deserialize_log_entry,
    serialize_notification,
    deserialize_notification,
    serialize_metric,
    deserialize_metric,
    serialize_websocket_message,
    deserialize_websocket_message,
    TaskProgressSerializer,
    LogEntrySerializer,
    NotificationSerializer,
    MetricSerializer,
    WebSocketMessageSerializer,
)
from .validators import (
    validate_task_id,
    validate_user_id,
    validate_progress_value,
    validate_status,
    validate_log_level,
    validate_notification_type,
    validate_metric_name,
    validate_task_metadata,
    validate_duration,
    validate_timestamp,
    ValidationError,
    ValidationResult,
)
from .formatters import (
    format_duration,
    format_percentage,
    format_timestamp,
    format_file_size,
    format_speed,
    format_progress_bar,
    format_status_badge,
    format_priority_badge,
    format_log_level,
    format_notification_title,
    truncate_text,
    format_error_message,
    format_summary,
)

__all__ = [
    # Serializers
    "serialize_task_progress",
    "deserialize_task_progress",
    "serialize_log_entry",
    "deserialize_log_entry",
    "serialize_notification",
    "deserialize_notification",
    "serialize_metric",
    "deserialize_metric",
    "serialize_websocket_message",
    "deserialize_websocket_message",
    "TaskProgressSerializer",
    "LogEntrySerializer",
    "NotificationSerializer",
    "MetricSerializer",
    "WebSocketMessageSerializer",
    # Validators
    "validate_task_id",
    "validate_user_id",
    "validate_progress_value",
    "validate_status",
    "validate_log_level",
    "validate_notification_type",
    "validate_metric_name",
    "validate_task_metadata",
    "validate_duration",
    "validate_timestamp",
    "ValidationError",
    "ValidationResult",
    # Formatters
    "format_duration",
    "format_percentage",
    "format_timestamp",
    "format_file_size",
    "format_speed",
    "format_progress_bar",
    "format_status_badge",
    "format_priority_badge",
    "format_log_level",
    "format_notification_title",
    "truncate_text",
    "format_error_message",
    "format_summary",
]
