"""Platform utilities package.

This package contains utility functions for platform operations,
including validation, serialization, and formatting utilities.
"""

from .validators import (
    validate_platform_name,
    validate_api_endpoint,
    validate_checksum,
    validate_file_size,
    validate_skill_id,
    validate_skill_version,
    validate_platform_config,
    validate_deployment_config,
    validate_platform_list,
    validate_compatibility_score,
    validate_json_structure,
    validate_datetime_range,
    validate_pagination_params,
    validate_skill_format,
    validate_retry_config,
    validate_health_check_params,
)

from .serializers import (
    serialize_platform,
    serialize_deployment,
    serialize_compatibility_check,
    serialize_platform_list,
    serialize_deployment_list,
    serialize_compatibility_check_list,
    serialize_platform_summary,
    serialize_deployment_summary,
    serialize_compatibility_summary,
    serialize_deployment_progress,
    serialize_platform_health,
    serialize_compatibility_report,
    serialize_to_json,
    serialize_to_pretty_json,
    deserialize_from_json,
    serialize_deployment_statistics,
    serialize_platform_statistics,
    serialize_compatibility_statistics,
)

from .formatters import (
    format_platform_display_name,
    format_platform_status,
    format_platform_type,
    format_deployment_status,
    format_deployment_status_with_details,
    format_compatibility_status,
    format_compatibility_score,
    format_file_size,
    format_duration,
    format_datetime,
    format_datetime_short,
    format_health_status,
    format_platform_list_display,
    format_deployment_list_display,
    format_compatibility_list_display,
    format_deployment_progress,
    format_issues_by_severity,
    format_recommendations_by_priority,
    format_platform_comparison,
    format_deployment_statistics,
    format_platform_statistics,
    format_compatibility_statistics,
    format_error_message,
    format_notification_message,
)

__all__ = [
    # Validation utilities
    "validate_platform_name",
    "validate_api_endpoint",
    "validate_checksum",
    "validate_file_size",
    "validate_skill_id",
    "validate_skill_version",
    "validate_platform_config",
    "validate_deployment_config",
    "validate_platform_list",
    "validate_compatibility_score",
    "validate_json_structure",
    "validate_datetime_range",
    "validate_pagination_params",
    "validate_skill_format",
    "validate_retry_config",
    "validate_health_check_params",
    # Serialization utilities
    "serialize_platform",
    "serialize_deployment",
    "serialize_compatibility_check",
    "serialize_platform_list",
    "serialize_deployment_list",
    "serialize_compatibility_check_list",
    "serialize_platform_summary",
    "serialize_deployment_summary",
    "serialize_compatibility_summary",
    "serialize_deployment_progress",
    "serialize_platform_health",
    "serialize_compatibility_report",
    "serialize_to_json",
    "serialize_to_pretty_json",
    "deserialize_from_json",
    "serialize_deployment_statistics",
    "serialize_platform_statistics",
    "serialize_compatibility_statistics",
    # Formatting utilities
    "format_platform_display_name",
    "format_platform_status",
    "format_platform_type",
    "format_deployment_status",
    "format_deployment_status_with_details",
    "format_compatibility_status",
    "format_compatibility_score",
    "format_file_size",
    "format_duration",
    "format_datetime",
    "format_datetime_short",
    "format_health_status",
    "format_platform_list_display",
    "format_deployment_list_display",
    "format_compatibility_list_display",
    "format_deployment_progress",
    "format_issues_by_severity",
    "format_recommendations_by_priority",
    "format_platform_comparison",
    "format_deployment_statistics",
    "format_platform_statistics",
    "format_compatibility_statistics",
    "format_error_message",
    "format_notification_message",
]